### ISSUE TITLE
Prevent collapsing whitespace in PHP tags

### ISSUE THREAD

**Issue by remibreton** [gruntjs/grunt-contrib-htmlmin#101]
Using `grunt-contrib-htmlmin 0.4.0`, collapsing whitespace also affects PHP tags. This is a code-breaking issue when using single line comments in PHP.

```html
<p>
    <?php
		// Test
		echo "Hello!";
    ?>
</p>
```

Get minified to:
```html
<p><?php // Test echo "Hello!"; ?></p>
```

I know that `grunt-contrib-htmlmin` is an HTML minifier, but I think it's an incredible feature to PHP while I HTML and still benefit from the minifier. I just wish it would ignore `<?`, `<?php` & `?>` before collapsing whitespace.

Apologizes if this issue was raised before!

**Comment by sindresorhus** [comment]
From the readme:

> *Issues with the output should be reported on the `htmlmin` [issue tracker](https://github.com/kangax/html-minifier/issues/new).*
