### ISSUE TITLE
Removing quotes can lead to invalid expressions

### ISSUE THREAD

**Issue by Javarome** [gruntjs/grunt-contrib-htmlmin#102]
When putting expressions in attributes, such as `<div ng-show="myList.length>0">`, removing the quotes lead to interpret `>` as a tag closing and so leads to output a `0>` because htmlmin generates `<div ng-show=myList.length> 0>`.

Of course a workaround is to disable the quotes removal, but this is losing an opportunity to remove a lot of quotes, whereas the parser could just avoid it if it detects a `>` in the attribute expression.

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt-contrib-htmlmin/issues/101#issuecomment-75913207

**Comment by az8321550** [comment]
? where is the answer?

**Comment by Hank-wood** [comment]
? where is the answer? +1
like this hava same issues
 <td> {{ value.number2<10?'0'+value.number2:value.number2 }} </td>
