### ISSUE TITLE
Can't get my minified file html to write

### ISSUE THREAD

**Issue by johnasp** [gruntjs/grunt-contrib-htmlmin#103]
Hi - I've got this Grunt task all up and running OK but the file refusing to write.  I want to place my minified html file in a 'build' folder but when I run the task it just does not write the file at all.  I have minified js and smushed images being writted to my build folder fine, but for some reason this is refusing to work.

Any suggestions?  Copy of my Gruntfile below:

     htmlmin: {
           dist: {
              options: {
                 removeComments: true,
                 collapseWhitespace: true
              },
              files: [{
                 expand: true,
                 cwd: 'src',
                 src: '**/*.html',
                 dest: 'build/'
              }]
           }
        }

**Comment by sindresorhus** [comment]
http://stackoverflow.com/questions/ask
