### ISSUE TITLE
Unable to minification an angular directive with the html param "multiple"

### ISSUE THREAD

**Issue by azachar** [gruntjs/grunt-contrib-htmlmin#109]
Hey There!

I have a directive that has the following jade code

```
   gallery(multiple='festivals')
```

After the minification I've got 
```
   <gallery multiple />
```

When I refactored the param name to ``combine`` instead of ``multiple`` it started to work. E.g. I've got this:

```
   <gallery combine=festivals />
```

 Is this bug or a feature?

Thank you for your help and your answer.

**Comment by sindresorhus** [comment]
The `multiple` attribute is defined by the HTML spec as a boolean, so the value is removed as it should be moot.

Any issue with the output however, as explicitly mentioned in the readme btw, should be opened here:
https://github.com/kangax/html-minifier/issues

**Comment by azachar** [comment]
Thanks for your reply!
