### ISSUE TITLE
HTMLMin crashes terminal window if there is a piece of quoted text in the html tag without an attribute name

### ISSUE THREAD

**Issue by strets123** [gruntjs/grunt-contrib-htmlmin#110]
On ~v0.3

I had a file with the following code snippet:

```
<a ng-if="!proj.editor" disabled title="You do not have permission to edit {{proj.project_type.show_compounds == true ? 'compounds' : 'items' }} on this project. Please ask an administrator for details." role="button" "btn btn-sm btn-default"><span class="glyphicon glyphicon-plus"></span> Add {{project.project_type.show_compounds == true ? 'compound' : 'item' }}</a>
```

The attribute name class= is missing from the above HTML after role="button", htmlmin makes  the terminal window window unresponsive instead of throwing an exception when trying to minify this.

**Comment by vladikoff** [comment]
Seems like an htmlmin bug, please file an issue under https://github.com/kangax/html-minifier

> Issues with the output should be reported on the htmlmin issue tracker.
