### ISSUE TITLE
javascript < is evaluated as invalid html and throws parse error 

### ISSUE THREAD

**Issue by mfeliciano** [gruntjs/grunt-contrib-htmlmin#112]
See https://github.com/ericclemmons/grunt-angular-templates/issues/102

Happens with grunt-contrib-htmlmin 0.4.0 release.

**Comment by vladikoff** [comment]
is it an issue with https://github.com/kangax/html-minifier ?

**Comment by mfeliciano** [comment]
Yes, looks like https://github.com/kangax/html-minifier/issues/282 is about the same issue and [this comment](https://github.com/kangax/html-minifier/issues/282#issuecomment-58750389) provides a solution.

Closing out this ticket.
