### ISSUE TITLE
Unable to minify *.html

### ISSUE THREAD

**Issue by julmot** [gruntjs/grunt-contrib-htmlmin#114]
Using

```javascript
files: {
 'dest/': 'src/*.html'
}
```

will not work.

**Comment by julmot** [comment]
I found this page explaining the usage: http://www.sitepoint.com/5-grunt-tasks-improve-performance-website/
I can only say that it is a bad documentation if I need to find the usage examples in other pages...

**Comment by Yappli** [comment]
Thanks for opening this issue @julmot, it helps.

**Comment by julmot** [comment]
you're welcome!
