### ISSUE TITLE
How to activate minifyJS

### ISSUE THREAD

**Issue by ralbion** [gruntjs/grunt-contrib-htmlmin#124]
Hi,

This is working great but how do I set this up to allow inline JavaScript to be minified? The html-minifier options page just states it 'uses UglifyJS'. I have uglify-js installed.

Thanks in advance.

**Comment by karensg** [comment]
Di you load it in grunt with `grunt.loadNpmTasks`?

**Comment by ralbion** [comment]
Sorry, it's working now. But it certainly wasn't working immediately following the install of UglifyJS. Yes I did have it loaded in the Gruntfile.
