### ISSUE TITLE
CDATA

### ISSUE THREAD

**Issue by piensaenpixel** [gruntjs/grunt-contrib-htmlmin#133]
Hi, is there any way for keeping CDATA comments?

**Comment by kirteshjain** [comment]
try removeCommentsFromCDATA: false

**Comment by jay-cz** [comment]
I have the same issue... I found following options:        

       removeCommentsFromCDATA: false,
       removeCDATASectionsFromCDATA: false,

however, none of it is working... Any other hint?

**Comment by kirteshjain** [comment]
I eventually moved to use htmlcompressor library .  that library just remove the extra spaces from html

**Comment by XhmikosR** [comment]
Please ask upstream.
