### ISSUE TITLE
difficult to use 

### ISSUE THREAD

**Issue by Simple2012hcz** [gruntjs/grunt-contrib-htmlmin#134]
we have many html files to min,we can not write one after one to finish,we need dir config to finish it.

**Comment by kirteshjain** [comment]
you can select multiple files using it e.g below in files 
htmlmin: {
             dist: {
                options: { 				    				
                      collapseWhitespace: true,		
					  removeComments: true,
										 
                },
                files: [{
                    expand: true,
                    cwd: 'app',
                     src: ['src/**/*.html',
						   '*.html'],					
                    dest: 'dist'
                }]
            }
        },
