### ISSUE TITLE
autogenerated tags included

### ISSUE THREAD

**Issue by kirteshjain** [gruntjs/grunt-contrib-htmlmin#135]
Hi I have set the includeAutoGeneratedTags: false in options to false but still I see autogenerated tags in my minified html.

When I used the minifier service here and set the autogenerated unchecked i get the correct minified html but not when I do it in code

**Comment by XhmikosR** [comment]
Does this still happen with the latest version?

**Comment by XhmikosR** [comment]
Closing due to lack of reply. Also, if it's still valid, it would be an upstream issue.
