### ISSUE TITLE
Removing space before <br> tag

### ISSUE THREAD

**Issue by VitalijPetras** [gruntjs/grunt-contrib-htmlmin#139]
Sometimes you want to have` <br>` tag in text. In my situation i need to separate text with `<br>` in desktop, but i dont need to do it in mobile. So after some resolution - lets say 
```
@media (max-width:959px){
br{display:none}
}
```
you hide this br and text should be seen like normal withou `<br>` tag.

The problem is, that plugin removes spaces before and after `<br>` tag and it looks like this (screen)
![screen](https://cloud.githubusercontent.com/assets/29103850/26645963/2fd1ecc6-463a-11e7-9f10-42d7f9acfed0.jpg)
![snimek obrazovky 2017-05-31 v 19 50 58](https://cloud.githubusercontent.com/assets/29103850/26646065/8a2c18e0-463a-11e7-92d3-2d1fe40aa4f3.png)

**Comment by XhmikosR** [comment]
> *Issues with the output should be reported on the `htmlmin` [issue tracker](https://github.com/kangax/html-minifier/issues/new).*
