### ISSUE TITLE
minifyJS bare_returns

### ISSUE THREAD

**Issue by cohenstyle** [gruntjs/grunt-contrib-htmlmin#143]
Passing {parse:{bare_returns: true}} to minifyJS doesn't cause an error but doesn't seem to make UglifyJS allow bare_returns in inline scripts.
Could this be an issue with the way inline scripts are passed to UglifyJS?

For context, the bare_returns flag allows uglify to parse javascript where there is a top level return statement, which is required by some templating libraries.

**Comment by XhmikosR** [comment]
All options are passed as is to html-minifier which in turns passes them to uglify.
