### ISSUE TITLE
Htmlmin stucks when there is handlebars condition inside the element

### ISSUE THREAD

**Issue by fizerkhan** [gruntjs/grunt-contrib-htmlmin#20]
login.html has password tag which needs to focused when there is an error.

``` html
<input type="password" class="required input-block-level" placeholder="Password" name="password" value="{{password}}" maxlength="70" required 
{{#if error}}autofocus="autofocus" {{/if}} >
```

The htmlmin hangs when processing this html file.

**Comment by bdemauro** [comment]
Htmlmin doesn't accept custom properties at HTML level, BUT if you add it inside the double quotes it will work: **autofocus="{{#if error}}autofocus{{/if}}"**

<input type="password" class="required input-block-level" placeholder="Password" name="password" value="{{password}}" maxlength="70" required autofocus="{{#if error}}autofocus{{/if}}">

Not perfect, but solves your issue.

**Comment by stephengardner** [comment]
Does anyone have a sample customAttrSurround that works?
