### ISSUE TITLE
No Minification - Empty Task

### ISSUE THREAD

**Issue by DougReynolds** [gruntjs/grunt-contrib-htmlmin#32]
I am using the following task configuration to try to get minification working:

``` javascript
htmlmin: {
    options: {
        removeComments: true,
        collapseWhitespace: true
    },
    files: {
        'build/src/index.html': 'src/index.html'  // 'destination': 'source'
    }
},
```

I am attempting to minify an html skeleton file which contains some angularJS directives, scripts, links, nothing else.  I've even removed the angularJS directives with no change in behavior.

Basically, this is the best way to describe the behavior (nothing):
Running "uglify:dist" (uglify) task
File "build/scripts/main.min.js" created.

Running "htmlmin:files" (htmlmin) task

Running "cssmin:compress" (cssmin) task
File build/styles/main.min.css created.

**Comment by Buom01** [comment]
In my case, it's was because the previous action isn't sync.
So the previous action write file after htmlmin
