### ISSUE TITLE
htmlmin stalls on error in html

### ISSUE THREAD

**Issue by kdekooter** [gruntjs/grunt-contrib-htmlmin#38]
I had this obvious typo in my code:

``` html
<table class="contentTable"">
```

The result was a stall. A proper exception message would have been nice.

**Comment by jwanglof** [comment]
@mattrw89 Also owe you a beer, thanks to your post I checked for typos and not closed tags and I had an unclosed tag.

**Comment by mattrw89** [comment]
@jwanglof Glad to be of help!

**Comment by hbmartin** [comment]
+1 for error messages

**Comment by flaurian** [comment]
+1 for exception catch. Still don't know why it's hanging in my project

**Comment by jafcobend** [comment]
I'm new to grunt and this bug has cost me an obscene amount of time. So I thought I'd post something that helped me out considerably. Running "grunt htmlmin -v". This would spit out file names until it gets to the file with the typo in it. I was able to do this without installing the html grunt task.

**Comment by sterlingstokes** [comment]
+1 Glad to have found this thread early in the debugging process but an exception would certainly be a bit more smooth for other folks in the future. For reference, my issue was caused by a missing "=" in an attribute: ```name"myName"``` instead of ```name="myName"```.
