### ISSUE TITLE
htmlmin hangs with no diagnostic if you have }> in your html

### ISSUE THREAD

**Issue by mark0978** [gruntjs/grunt-contrib-htmlmin#53]
I had a curly brace slip outside the quotes and cause htmlmin to go into some kind of inifinte loop.

The line it hung on looked like this:

<fieldset ng-disabled="!jobEditEnabled || !validEmployer()" ng-class="{masked: loadingEmployerContacts}"}>

See the last 2 characters on the line

**Comment by MarijnStevens** [comment]
This kind of sucks, even with --verbose I have no glue whatsoever where it can be.
