### ISSUE TITLE
Issue with reducing <input type="text" ...> to just <input ...>

### ISSUE THREAD

**Issue by EdBoucher** [gruntjs/grunt-contrib-htmlmin#73]
If you're styling forms, this reduction will break any CSS that targets text inputs. I may be missing something but I've yet to find the code that makes this conditional on finding a selector in a CSS file. Should this be an configuration option, or just removed? 

JSFiddle: http://jsfiddle.net/jeanpaulsoftware/4P5R7/

**Comment by almandot** [comment]
Thank you yoyeung you finally solved a giant headache when I found this.
